// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "aa4c14b2-730b-4461-9557-54fba97d561f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPpmChange();
void onForventChange();

float ppm;
bool forvent;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(ppm, READWRITE, 2 * SECONDS, onPpmChange);
  ArduinoCloud.addProperty(forvent, READWRITE, ON_CHANGE, onForventChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
